networks:
  amsearch:

volumes:
  postgres:

services:
  postgres:
    image: paradedb/paradedb:latest
    cap_add:
      - SYS_NICE
    env_file: docker/postgres.env
    ports:
      - 5432:5432
    networks:
      - amsearch
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: amsearch
    env_file: docker/web.env
    ports:
      - 8000:8000
    networks:
      - amsearch
    volumes:
      - ./models/indobert-ams:/models/indobert-ams
      - ./models/stemming-vocab.txt:/models/stemming-vocab.txt
    depends_on:
      - postgres
