version: "3.8"

networks:
  amsearch:

volumes:
  postgres:

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    cap_add:
      - SYS_NICE
    restart: always
    env_file: postgres.env
    ports:
      - 5432:5432
    networks:
      - amsearch
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./seed:/docker-entrypoint-initdb.d

  web:
    build: amsearch
    restart: always
    env_file: web.env
    ports:
      - 8000:8000
    networks:
      - amsearch
    volumes:
      - ./data:/data
    depends_on:
      - postgres
