[project]
name = "project-2023-amsearch"
version = "0.1.0"
description = "AMSearch"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Math, Data, and Machine Learning
    "numpy<1.29",
    "scipy==1.12",
    "pandas>=2.2.2",
    "openpyxl>=3.1.5",
    "pydantic>=2.10.4",
    "scikit-learn>=1.3.0",
    "joblib>=1.4.2",
    "umap-learn>=0.5.7",
    # NLP
    "nltk>=3.9.1",
    "gensim>=4.3.2",
    "thefuzz>=0.22.1",
    "pysastrawi>=1.2.0",
    # LLM
    "beir>=2.0.0",
    "torch>=1.11.0",
    "bm25s>=0.2.6",
    "openai>=1.58.1",
    "google-genai>=1.28.0",
    "huggingface-hub>=0.25.2",
    "transformers[torch]>=4.47.1",
    "sentence-transformers>=2.2.2",
    # Web App and Database
    "flask>=2.3.2",
    "flask-login>=0.6.2",
    "flask-sqlalchemy>=3.0.3",
    "gunicorn>=21.2.0",
    "werkzeug>=2.3.6",
    "pgvector>=0.2.0",
    "psycopg2-binary>=2.9.6",
    "python-dotenv>=1.0.0",
    "markupsafe<3.0.2",
    # Notebook and Utils
    "ruff>=0.8.4",
    "tqdm>=4.67.1",
    "rich>=13.9.4",
    "requests>=2.31.0",
    "ipykernel>=6.29.5",
    "setuptools>=72.2.0",
    "seaborn>=0.13.2",
    "scienceplots>=2.1.1",
    "matplotlib>=3.10.0",
]

[tool.uv]
index-strategy = "unsafe-best-match"
extra-index-url = ["https://download.pytorch.org/whl/cpu"]
